export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO';
export const AGREGAR_PRODUCTO_EXITO = 'AGREGAR_PRODUCTO_EXITO';
export const AGREGAR_PRODUCTO_ERROR = 'AGREGAR_PRODUCTO_ERROR';

export const COMENZAR_DESCARGA_PRODUCTOS = 'COMENZAR_DESCARGA_PRODUCTOS';
export const DESCARGA_PRODUCTOS_EXITO = 'DESCARGA_PRODUCTOS_EXITO';
export const DESCARGA_PRODUCTOS_ERROR = 'DESCARGA_PRODUCTOS_ERROR';

export const OBTENER_PRODUCTO_ELIMINAR = 'OBTENER_PRODUCTO_ELIMINAR';
export const PRODUCTO_ELIMINADO_EXITO = 'PRODUCTO_ELIMINADO_EXITO';
export const PRODUCTO_ELIMINADO_ERROR = 'PRODUCTO_ELIMINADO_ERROR';

export const OBTENER_PRODUCTO_EDITAR = 'OBTENER_PRODUCTO_EDITAR';
export const COMENZAR_EDICION_PRODUCTO = 'COMENZAR_EDICION_PRODUCTO';
export const PRODUCTO_EDITADO_EXITO = 'PRODUCTO_EDITADO_EXITO';
export const PRODUCTO_EDITADO_ERROR = 'PRODUCTO_EDITADO_ERROR';

export const MOSTRAR_ALERTA = 'MOSTRAR_ALERTA';
export const OCULTAR_ALERTA = 'OCULTAR_ALERTA';

export const SHOW_HEADER = 'SHOW_HEADER';
export const HIDE_HEADER = 'HIDE_HEADER';
export const HIDE_FOOTER = 'HIDE_FOOTER';
export const SHOW_FOOTER = 'SHOW_FOOTER';


export const AUTH_SING_IN_SUCCESS = 'AUTH_SING_IN_SUCCESS'
export const AUTH_SIGN_IN_ERROR = 'AUTH_SIGN_IN_ERROR';
export const AUTH_SING_UP_SUCCESS = 'AUTH_SING_UP_SUCCESS'
export const AUTH_SIGN_UP_ERROR = 'AUTH_SIGN_UP_ERROR';
export const AUTH_SING_OUT_SUCCESS = 'AUTH_SING_OUT_SUCCESS'

export const SELECT_TYPE_SHIPPING_DISPATCH = 'SELECT_TYPE_SHIPPING_DISPATCH'
export const SELECT_TYPE_SHIPPING_OFFICE = 'SELECT_TYPE_SHIPPING_OFFICE';

export const INIT_CART_SHOP = 'INIT_CART_SHOP';
export const UPDATE_CART_SHOP = 'UPDATE_CART_SHOP';
export const CLEAR_CART_SHOP = 'CLEAR_CART_SHOP';
export const FETCH_CART_SHOP = 'FETCH_CART_SHOP';
export const FETCH_CART_SHOP_ERROR = 'FETCH_CART_SHOP_ERROR';
export const FETCH_CART_SHOP_SUCCESS = 'FETCH_CART_SHOP_ERROR';

export const FETCH_REGION = 'FETCH_REGION';
export const FETCH_COMMUNE = 'FETCH_COMMUNE';
export const FETCH_CITY = 'FETCH_CITY';

export const AUTH_AS_ADMIN = 'AUTH_AS_ADMIN';
export const AUTH_AS_USER = 'AUTH_AS_USER';

export const SET_STATUS_CONFIGURATION = 'SET_STATUS_CONFIGURATION';