
export const SHOW_HEADER = 'SHOW_HEADER';
export const HIDE_HEADER = 'HIDE_HEADER';
export const HIDE_FOOTER = 'HIDE_FOOTER';
export const SHOW_FOOTER = 'SHOW_FOOTER';


export const AUTH_SING_IN_SUCCESS = 'AUTH_SING_IN_SUCCESS'
export const AUTH_SIGN_IN_ERROR = 'AUTH_SIGN_IN_ERROR';
export const AUTH_SING_UP_SUCCESS = 'AUTH_SING_UP_SUCCESS'
export const AUTH_SIGN_UP_ERROR = 'AUTH_SIGN_UP_ERROR';
export const AUTH_SING_OUT_SUCCESS = 'AUTH_SING_OUT_SUCCESS'

export const SELECT_TYPE_SHIPPING_DISPATCH = 'SELECT_TYPE_SHIPPING_DISPATCH'
export const SELECT_TYPE_SHIPPING_OFFICE = 'SELECT_TYPE_SHIPPING_OFFICE';

export const INIT_CART_SHOP = 'INIT_CART_SHOP';
export const UPDATE_CART_SHOP = 'UPDATE_CART_SHOP';
export const DELETE_CART_ITEM = 'DELETE_CART_ITEM'
export const CLEAR_CART_SHOP = 'CLEAR_CART_SHOP';
export const FETCH_CART_SHOP = 'FETCH_CART_SHOP';
export const FETCH_CART_SHOP_ERROR = 'FETCH_CART_SHOP_ERROR';
export const FETCH_CART_SHOP_SUCCESS = 'FETCH_CART_SHOP_ERROR';
export const MODAL_CART_SHOP = 'MODAL_CART_SHOP'


export const AUTH_AS_ADMIN = 'AUTH_AS_ADMIN';
export const AUTH_AS_USER = 'AUTH_AS_USER';

export const SET_STATUS_CONFIGURATION = 'SET_STATUS_CONFIGURATION';

export const FETCH_REGION = 'FETCH_REGION';
export const FETCH_COMMUNE = 'FETCH_COMMUNE';
export const FETCH_CITY = 'FETCH_CITY';
export const FETCH_BRANCH = 'FETCH_BRANCH';
export const FETCH_ADDRESS_ERROR = 'FETCH_ADDRESS_ERROR';
export const GET_ORDER_SET_ADDRESS = 'GET_ORDER_SET_ADDRESS';

export const REGION_SELECT = 'REGION_SELECT';
export const CITY_SELECT = 'CITY_SELECT';
export const COMMUNE_SELECT = 'COMUNE_SELECT';
export const CLEAR_CITY = 'CLEAR_CITY';
export const CLEAR_COMMUNE = 'CLEAR_COMMUNE';
export const SAVE_ADDRESS = 'SAVE_ADDRESS';

export const COMPLETE_DEPTO = 'COMPLETE_DEPTO';
export const COMPLETE_OFFICE = 'COMPLETE_OFFICE'

export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const ERROR_CATEGORY = 'ERROR_CATEGORY';
export const ERROR_PRODUCT = 'ERROR_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const CREATE_NEW_PRODUCT = 'CREATE_NEW_PRODUCT'

export const DISABLE_PRODUCT = 'DISABLE_PRODUCT'
export const ENABLE_PRODUCT = 'ENABLE_PRODUCT'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const CANCEL_EDIT = 'CANCEL_EDIT'

export const PRODUCT_TO_CREATE = "PRODUCT_TO_CREATE"
export const PRODUCT_TO_DELETE = 'PRODUCT_TO_DELETE'
export const PRODUCT_TO_EDIT = 'PRODUCT_TO_EDIT'

export const SHOW_MODAL_CATEGORY = 'SHOW_MODAL_CATEGORY'
export const SHOW_MODAL_ADD_NEW_PRODUCT = 'SHOW_MODAL_ADD_NEW_PRODUCT'

export const ADD_NEW_ADDRESS = 'ADD_NEW_ADDRESS'

export const FIND_COMMUNE_BY_ID = 'FIND_COMMUNE_BY_ID'

export const SELECT_BRANCH_OFFICE = 'SELECT_BRANCH_OFFICE'

export const FULL_ADDRES_FOR_SELL = 'FULL_ADDRES_FOR_SELL'